setwd("/scratch/richards/tomoko.nakanishi/09.COVID19/05.BQC/01.genotypeQC/v5.0/")

tmpA <- fread("bqc-bAvsBCDEFGHIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpA$SNP, "A"), "het.fisher.remove.bA.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpB <- fread("bqc-bBvsACDEFGHIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpB$SNP, "B"), "het.fisher.remove.bB.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpC <- fread("bqc-bCvsABDEFGHIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpC$SNP, "C"), "het.fisher.remove.bC.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpD <- fread("bqc-bDvsABCEFGHIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpD$SNP, "D"), "het.fisher.remove.bD.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpE <- fread("bqc-bEvsABCDFGHIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpE$SNP, "E"), "het.fisher.remove.bE.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpF <- fread("bqc-bFvsABCDEGHIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpF$SNP, "F"), "het.fisher.remove.bF.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpG <- fread("bqc-bGvsABCDEFHIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpG$SNP, "G"), "het.fisher.remove.bG.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpH <- fread("bqc-bHvsABCDEFGIJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpH$SNP, "H"), "het.fisher.remove.bH.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpI <- fread("bqc-bIvsABCDEFGHJKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpI$SNP, "I"), "het.fisher.remove.bI.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpJ <- fread("bqc-bJvsABCDEFGHIKLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpJ$SNP, "J"), "het.fisher.remove.bJ.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpK <- fread("bqc-bKvsABCDEFGHIJLMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpK$SNP, "K"), "het.fisher.remove.bK.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpL <- fread("bqc-bLvsABCDEFGHIJKMNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpL$SNP, "L"), "het.fisher.remove.bL.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpM <- fread("bqc-bMvsABCDEFGHIJKLNOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpM$SNP, "M"), "het.fisher.remove.bM.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpN <- fread("bqc-bNvsABCDEFGHIJKLMOPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpN$SNP, "N"), "het.fisher.remove.bN.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpO <- fread("bqc-bOvsABCDEFGHIJKLMNPQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpO$SNP, "O"), "het.fisher.remove.bO.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpP <- fread("bqc-bPvsABCDEFGHIJKLMNOQRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpP$SNP, "P"), "het.fisher.remove.bP.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpQ <- fread("bqc-bQvsABCDEFGHIJKLMNOPRSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpQ$SNP, "Q"), "het.fisher.remove.bQ.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpR <- fread("bqc-bRvsABCDEFGHIJKLMNOPQSTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpR$SNP, "R"), "het.fisher.remove.bR.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpS <- fread("bqc-bSvsABCDEFGHIJKLMNOPQRTUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpS$SNP, "S"), "het.fisher.remove.bS.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpT <- fread("bqc-bTvsABCDEFGHIJKLMNOPQRSUVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpT$SNP, "T"), "het.fisher.remove.bT.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpU <- fread("bqc-bUvsABCDEFGHIJKLMNOPQRSTVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpU$SNP, "U"), "het.fisher.remove.bU.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpV <- fread("bqc-bVvsABCDEFGHIJKLMNOPQRSTUWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpV$SNP, "V"), "het.fisher.remove.bV.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpW <- fread("bqc-bWvsABCDEFGHIJKLMNOPQRSTUVXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpW$SNP, "W"), "het.fisher.remove.bW.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpU <- fread("bqc-bUvsABCDEFGHIJKLMNOPQRSTVWXYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpU$SNP, "U"), "het.fisher.remove.bU.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpX <- fread("bqc-bXvsABCDEFGHIJKLMNOPQRSTUVWYZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpX$SNP, "X"), "het.fisher.remove.bX.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpY <- fread("bqc-bYvsABCDEFGHIJKLMNOPQRSTUVWXZabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpY$SNP, "Y"), "het.fisher.remove.bY.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpZ <- fread("bqc-bZvsABCDEFGHIJKLMNOPQRSTUVWXYabcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpZ$SNP, "Z"), "het.fisher.remove.bZ.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpa <- fread("bqc-bavsABCDEFGHIJKLMNOPQRSTUVWXYZbcde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpa$SNP, "a"), "het.fisher.remove.ba.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpb <- fread("bqc-bbvsABCDEFGHIJKLMNOPQRSTUVWXYZacde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpb$SNP, "b"), "het.fisher.remove.bb.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpc <- fread("bqc-bcvsABCDEFGHIJKLMNOPQRSTUVWXYZabde-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpc$SNP, "c"), "het.fisher.remove.bc.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpd <- fread("bqc-bdvsABCDEFGHIJKLMNOPQRSTUVWXYZabce-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpd$SNP, "d"), "het.fisher.remove.bd.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpe <- fread("bqc-bevsABCDEFGHIJKLMNOPQRSTUVWXYZabcd-qc3-EUR.het.fisher.p.txt") %>% filter(fisher.p < 1e-12)
write.table(cbind(tmpd$SNP, "e"), "het.fisher.remove.be.snp_id", sep=" ", quote=F, col.names = F, row.names = F)

tmpA <- fread("bqc-bA-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpA$SNP, "A"), "hwe.remove.bA.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpB <- fread("bqc-bB-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpB$SNP, "B"), "hwe.remove.bB.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpC <- fread("bqc-bC-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpC$SNP, "C"), "hwe.remove.bC.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpD <- fread("bqc-bD-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpD$SNP, "D"), "hwe.remove.bD.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpE <- fread("bqc-bE-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpE$SNP, "E"), "hwe.remove.bE.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpF <- fread("bqc-bF-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpF$SNP, "F"), "hwe.remove.bF.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpG <- fread("bqc-bG-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpG$SNP, "G"), "hwe.remove.bG.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpH <- fread("bqc-bH-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpH$SNP, "H"), "hwe.remove.bH.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpI <- fread("bqc-bI-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpI$SNP, "I"), "hwe.remove.bI.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpJ <- fread("bqc-bJ-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpJ$SNP, "J"), "hwe.remove.bJ.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpK <- fread("bqc-bK-qc3-EUR.hwe") %>% filter(P < 1e-12)
write.table(cbind(tmpK$SNP, "K"), "hwe.remove.bK.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpL <- fread("bqc-bL-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpL$SNP, "L"), "hwe.remove.bL.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpM <- fread("bqc-bM-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpM$SNP, "M"), "hwe.remove.bM.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpN <- fread("bqc-bN-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpN$SNP, "N"), "hwe.remove.bN.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpO <- fread("bqc-bO-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpO$SNP, "O"), "hwe.remove.bO.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpP <- fread("bqc-bP-qc3-EUR.hwe") %>% filter(P < 1e-12)
write.table(cbind(tmpP$SNP, "P"), "hwe.remove.bP.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpQ <- fread("bqc-bQ-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpQ$SNP, "Q"), "hwe.remove.bQ.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpR <- fread("bqc-bR-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpR$SNP, "R"), "hwe.remove.bR.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpS <- fread("bqc-bS-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpS$SNP, "S"), "hwe.remove.bS.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpT <- fread("bqc-bT-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpT$SNP, "T"), "hwe.remove.bT.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpU <- fread("bqc-bU-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpU$SNP, "U"), "hwe.remove.bU.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpV <- fread("bqc-bV-qc3-EUR.hwe") %>% filter(P < 1e-12)
write.table(cbind(tmpV$SNP, "V"), "hwe.remove.bV.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpW <- fread("bqc-bW-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpW$SNP, "W"), "hwe.remove.bW.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpX <- fread("bqc-bX-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpX$SNP, "X"), "hwe.remove.bX.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpY <- fread("bqc-bY-qc3-EUR.hwe") %>% filter(P < 1e-12)
write.table(cbind(tmpY$SNP, "Y"), "hwe.remove.bY.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpZ <- fread("bqc-bZ-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpZ$SNP, "Z"), "hwe.remove.bZ.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpa <- fread("bqc-ba-qc3-EUR.hwe") %>% filter(P < 1e-12)
write.table(cbind(tmpa$SNP, "a"), "hwe.remove.ba.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpb <- fread("bqc-bb-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpb$SNP, "b"), "hwe.remove.bb.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpc <- fread("bqc-bc-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpc$SNP, "c"), "hwe.remove.bc.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpd <- fread("bqc-bd-qc3-EUR.hwe") %>% filter(P < 1e-12)
#write.table(cbind(tmpd$SNP, "d"), "hwe.remove.bd.snp_id", sep=" ", quote=F, col.names = F, row.names = F)
tmpe <- fread("bqc-be-qc3-EUR.hwe") %>% filter(P < 1e-12)

